# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:17
from __future__ import unicode_literals

import audioselector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=audioselector.models.uploaded_song_file_name)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
