# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:24
from __future__ import unicode_literals

import audioselector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioselector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='media',
            field=models.FileField(upload_to=audioselector.models.uploaded_song_file_name),
        ),
    ]
